unbind C-b
set-option -g prefix C-a


bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

set-window-option -g mode-keys vi

set -sg escape-time 10

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

set -g @plugin 'catppuccin/tmux'

set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_flavour "macchiato"

run '~/.tmux/plugins/tpm/tpm'

